import { useRef } from 'react';
import { QRCodeSVG } from 'qrcode.react';

interface QRLabelProps {
  qrCode: string;
  productoNombre: string;
  ordenId: number;
  clienteNombre: string;
  acabado: string;
  size?: number;
  showPrint?: boolean;
}

export default function QRLabel({ qrCode, productoNombre, ordenId, clienteNombre, acabado, size = 80, showPrint = true }: QRLabelProps) {
  const qrRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    const w = window.open('', '_blank');
    if (!w) return;
    
    // Copy the actual SVG generated by qrcode.react
    const svgHtml = qrRef.current?.innerHTML || '';
    
    const css = `
      @page { margin: 0; size: 5.72cm 3.18cm; }
      body {
        font-family: Arial, Helvetica, sans-serif;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        background: white;
        color: black;
        width: 5.72cm;
        height: 3.18cm;
        overflow: hidden;
      }
      .label {
        width: 5.72cm;
        height: 3.18cm;
        padding: 0.15cm;
        box-sizing: border-box;
        display: flex;
        align-items: center;
        page-break-inside: avoid;
      }
      .qr-container {
        width: 2.3cm;
        height: 2.3cm;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
      }
      .qr-container svg {
        width: 100%;
        height: 100%;
      }
      .details {
        margin-left: 0.15cm;
        display: flex;
        flex-direction: column;
        justify-content: center;
        flex-grow: 1;
        overflow: hidden;
      }
      .branch-header {
        background: #0d9488;
        color: white;
        padding: 2px 4px;
        font-size: 6.5px;
        font-weight: 900;
        text-transform: uppercase;
        text-align: center;
        border-radius: 2px;
        margin-bottom: 2px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
      .title {
        font-size: 8px;
        font-weight: 900;
        text-transform: uppercase;
        margin: 0 0 1px 0;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
      .meta {
        font-size: 6.5px;
        margin: 0 0 1px 0;
        line-height: 1.1;
      }
      .sku {
        font-family: monospace;
        font-size: 6.5px;
        font-weight: bold;
        margin-top: 1px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
    `;

    w.document.write(`<html><head><title>Etiqueta ${qrCode}</title><style>${css}</style></head><body>
      <div class="label">
        <div class="qr-container">
          ${svgHtml}
        </div>
        <div class="details">
          <div class="branch-header">📍 ${clienteNombre || 'DECOR MUEBLERÍA'}</div>
          <h1 class="title">${productoNombre}</h1>
          <p class="meta"><strong>Ord:</strong> #${ordenId || 'STOCK'}</p>
          <p class="meta"><strong>Acabado:</strong> ${acabado || 'Rústico Natural'}</p>
          <div class="sku">${qrCode}</div>
        </div>
      </div>
      <script>window.onload=function(){setTimeout(window.print, 100);}</script>
    </body></html>`);
    w.document.close();
  };

  return (
    <div className="flex flex-col items-center gap-1.5">
      <div ref={qrRef} className="bg-white p-1.5 rounded-xl border border-stone-200 shadow-xs qr-label-svg-container">
        <QRCodeSVG value={qrCode} size={size} level="M" />
      </div>
      <p className="text-[10px] font-mono text-stone-500 text-center break-words w-full" style={{ maxWidth: size + 30 }}>{qrCode}</p>
      {showPrint && (
        <button onClick={handlePrint} className="text-xs text-teal-800 hover:text-teal-900 font-bold hover:underline flex items-center gap-1">
          🖨️ Imprimir
        </button>
      )}
    </div>
  );
}
