import { useRef } from 'react';
import { QRCodeSVG } from 'qrcode.react';

interface QRLabelProps {
  qrCode: string;
  productoNombre: string;
  ordenId: number;
  clienteNombre: string;
  acabado: string;
  size?: number;
  showPrint?: boolean;
}

export default function QRLabel({ qrCode, productoNombre, ordenId, clienteNombre, acabado, size = 80, showPrint = true }: QRLabelProps) {
  const qrRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    const w = window.open('', '_blank');
    if (!w) return;
    
    // Copy the actual SVG generated by qrcode.react
    const svgHtml = qrRef.current?.innerHTML || '';
    
    const css = `
      @page { margin: 0; size: auto; }
      body {
        font-family: Arial, Helvetica, sans-serif;
        margin: 0;
        padding: 10mm;
        box-sizing: border-box;
        background: white;
        color: black;
      }
      .label {
        width: 6.6cm;
        height: 2.5cm;
        padding: 0.2cm;
        box-sizing: border-box;
        display: flex;
        align-items: center;
        border: 1px dashed #ccc;
        page-break-inside: avoid;
      }
      .qr-container {
        width: 2.1cm;
        height: 2.1cm;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
      }
      .qr-container svg {
        width: 100%;
        height: 100%;
      }
      .details {
        margin-left: 0.2cm;
        display: flex;
        flex-direction: column;
        justify-content: center;
        flex-grow: 1;
        overflow: hidden;
      }
      .title {
        font-size: 10px;
        font-weight: 900;
        text-transform: uppercase;
        margin: 0 0 2px 0;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
      .meta {
        font-size: 8px;
        margin: 0 0 1px 0;
      }
      .sku {
        font-family: monospace;
        font-size: 8px;
        font-weight: bold;
        margin-top: 2px;
      }
    `;

    w.document.write(`<html><head><title>Etiqueta ${qrCode}</title><style>${css}</style></head><body>
      <div class="label">
        <div class="qr-container">
          ${svgHtml}
        </div>
        <div class="details">
          <h1 class="title">${productoNombre}</h1>
          <p class="meta"><strong>Ord:</strong> #${ordenId}</p>
          <p class="meta"><strong>Destino:</strong> ${clienteNombre}</p>
          <p class="meta"><strong>Acabado:</strong> ${acabado}</p>
          <div class="sku">${qrCode}</div>
        </div>
      </div>
      <script>window.onload=function(){setTimeout(window.print, 100);}</script>
    </body></html>`);
    w.document.close();
  };

  return (
    <div className="flex flex-col items-center gap-2">
      <div ref={qrRef} className="bg-white p-2 rounded-lg">
        <QRCodeSVG value={qrCode} size={size} level="M" />
      </div>
      <p className="text-[10px] font-mono text-zinc-400 text-center break-words w-full" style={{ maxWidth: size + 20 }}>{qrCode}</p>
      {showPrint && (
        <button onClick={handlePrint} className="text-[10px] text-amber-400 hover:text-amber-300 font-semibold hover:underline">
          🖨 Imprimir
        </button>
      )}
    </div>
  );
}
